### ISSUE TITLE
bug: #keys??

### ISSUE THREAD

**Issue by raymondsze** [panva/jose#27] opened 2019-05-29 09:32 UTC
**Describe the bug**
I got this when doing webpack bundle targeting "node".
```
ERROR in ./node_modules/@panva/jose/lib/jwks/keystore.js 40:2
Module parse failed: Unexpected character '#' (40:2)
You may need an appropriate loader to handle this file type.
|
| class KeyStore {
>   #keys
|
|   constructor (...keys) {
 @ ./node_modules/@panva/jose/lib/jwks/index.js 1:17-38
```
#keys should be not a valid variable name. Is it intended?

**To Reproduce**

Steps to reproduce the behaviour:

1.  
2.  
3.  

**Expected behaviour**

**Environment:**
 - @panva/jose version: [e.g. v1.0.0]
 - node version: [e.g. v12.0.0]

**Additional context**

 - [x] the bug is happening on latest @panva/jose too.
 - [x] i have tried DEBUG (see readme.md) and can see the issue is with the provider and not my code.
 - [x] i have searched the issues tracker on github for similar issues and couldn't find anything related.

**Comment by panva** [comment] 2019-05-29 09:35
Duplicate of #23. Do not transpile with tools not capable of handling esnext class fields.

**Closed by panva** 2019-05-29 09:35 UTC
Labels: bug

**Comment by panva** [comment] 2019-05-30 07:34
> You may need an appropriate loader to handle this file type.

This is even in your log :) `babel-eslint` is able to parse esnext syntax. That being said, i don't recommend or understand why transpile to a target which is node already.

**Comment by panva** [comment] 2019-08-15 19:31
#37 https://v8.dev/features/class-fields

**Comment by panva** [comment] 2019-08-22 19:04
I've made @panva/jose compatible with lts/dubnium, it is now being tested with Node.js `^10.13.0 || >=12.0.0` and Electron `^6.0.0`

It is not without caveats, but they are acceptable.
- Importing X.509 certificates and handling x5c is only supported when Node.js >= 12.0.0 runtime is detected
- OKP keys are only supported when Node.js >= 12.0.0 runtime is detected

**Comment by panva** [comment] 2020-11-19 16:23
A quick note, i've release a new major (v3.x) which is now a universal module with 0 dependencies and now works the same in the browser as well as node.
