### ISSUE TITLE
Node.js API used in jose/dist/browser/runtime/env.js on line 6

### ISSUE THREAD

**Issue by trm217** [panva/jose#421] opened 2022-06-28 19:48 UTC
### What happened?

I am using Jose in combination with Next.js (v12.2) middleware and an error is thrown due to `process.versions` being used inside `jose/dist/browser/runtime/env.js` on line 6. 
I suppose it could be replaced with simply checking `typeof process === 'object` to find out if it's node, since the only thing done in this file is to check if it's run inside node.

### Version

4.18.1

### Runtime

Browser

### Runtime Details

Next.js (v12.2) middleware / only browser api available

### Code to reproduce

Create a project with Next.js v12.2 and add `import * as jose from 'jose'` inside a middleware defined according to: https://nextjs.org/docs/advanced-features/middleware

### Required

- [X] I have searched the issues tracker and discussions for similar topics and couldn't find anything related.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/panva/jose/blob/main/CODE_OF_CONDUCT.md)

**Comment by panva** [comment] 2022-06-28 20:01
Please work out a gist/project i can clone and reproduce. Thank you.

Your report also lacks the actual error, its stacktrace, etc.

**Comment by trm217** [comment] 2022-06-28 20:20
No such thing as a stacktrace or an error since it crashes the application due to the compile checks before the code is even executed. 
process.versions is a Node.js api from what I see, and that's why I suppose the middleware seems to fail.
From what I can tell, that's probably also why `process.versions.node !== undefined;` is inside a try-catch (see snippit below from the above mentioned file)

```js
export function isNodeJs() {
    try {
        return process.versions.node !== undefined;
    }
    catch (_a) {
        return false;
    }
}
```

I'll attach a screenshot of the error shown by Next.js:
<img width="855" alt="image" src="https://user-images.githubusercontent.com/30313631/176276857-64dcadcc-d321-4aaa-bfb6-2e1eb88c1ce5.png">

**Comment by trm217** [comment] 2022-06-28 20:32
Interesting, I just noticed that you removed the above mentioned function `isNodeJS` with this commit [e06b97c](https://github.com/panva/jose/commit/e06b97c1aa0be332d93a754c66ec15b2a365d794). But is still included in the dist in our node-modules which loads jose 4.8.1

**Comment by acburdine** [comment] 2022-06-28 22:30
@trm217 I ran into this the other day as well, it looks like there hasn't been a release created since that commit. Once a new version is released, the issue should be resolved.

**Comment by Marcelx8** [comment] 2022-06-28 22:53
Same issue on my side. Just updated from a Next.js v12.1.7-canary.6 to v12.2.0 to have stable middleware, and now I'm sitting with this error before my PR XD 

```
const verified = await jwtVerify(token, new TextEncoder().encode(JWT_SECRET));
return verified.payload
```
Breaks on the `jwtVerify` with the error mentioned above: "You're using a Node.js API (process.versions at line: 6) which is not supported in the Edge Runtime that Middleware uses"

**Comment by panva** [comment] 2022-06-28 23:22
@leerob how do you envision universal libraries should be doing runtime detection?

This here seems like a regression in Next.js

**Comment by Marcelx8** [comment] 2022-06-28 23:28
There seems to be some possible workaround here: 
https://github.com/vercel/next.js/issues/36237#issuecomment-1117694528

Still verifying on my end

**Comment by panva** [comment] 2022-06-28 23:41
`v4.8.2` will be released shortly with the code from `main` which coincidentally removed the need for this anyway.

I'll leave this open as https://github.com/panva/jose/labels/triage so that @leerob @balazsorban44 can pitch in.

**Comment by Marcelx8** [comment] 2022-06-28 23:50
@panva - We appreciate your quick response!

**Comment by ScriptedAlchemy** [comment] 2022-06-29 00:12
if(options.nextRuntime === 'edge') {
new DefinePlugin() or require.resolve[dep] = false
}

Thatll let you control the edge build. you can either just skip importing it or use define plugin to inject the variable if need be

**Comment by acburdine** [comment] 2022-06-29 13:39
I can confirm that v4.8.3 (most recent version) fixes the build issue from next.js.

**Closed** 2022-07-04 13:18 UTC
Labels: waiting for feedback, triage
